name: migu
on:
  push:
  schedule:
    - cron: '0 */3 * * *'
jobs:
    build:
        runs-on: ubuntu-20.04
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
        - name: Clone source code
            run: |
            - git clone https://github.com/adai100/migu_video.git
            - '# git clone https://develop202:${GITHUB_TOKEN}@github.com/develop202/migu_video.git'
            - cd migu_video
            - '# 设置NPM源，提升安装速度'
            - npm config set registry https://registry.npmmirror.com
            - '# 执行编译命令 '
            - '# npm install && node fetchURLByWasm.js'
            - '# npm install && node fetchURLByAndroid.js'
            - npm install && node fetchURLByAndroidV2.js
            - git config user.name "Gitee流水线"
            - git config user.email "actions@githee.com"
            - git add .
            - '# gitee流水线提交 '
            - git diff --quiet && git diff --staged --quiet || git commit -m "Update by Gitee流水线"
            - '# git push -f https://dream-deve:${TOKEN}@gitee.com/dream-deve/migu_video.git main:main'
            - git push